### PR TITLE
Use lz4 crate instead of library and fix Morton-encoding

### LINKED ISSUE #60: Python: Build depends on local LZ4, which is only built during CI
The Python build script (`python/setup.py`) assumes that `liblz4` is available at `../lz4/lib`. But these libraries are only built by the CI workflows defined in `.github/workflows/python-module.yml`.

We should extract these steps from the CI workflows if we insist on building and packaging LZ4 ourselves. Instead, these steps should be part of the Python build script. Otherwise, local builds of the Python package are effectively broken.

### PR DESCRIPTION
**Pull request by normanrz**
This PR replaces the bundled `lz4` library with the `lz4` crate. This has the benefit that the `lz4` code will be statically linked into the `wkw` lib. Therefore, we save a lot of build code (for all 3 platforms) and only need to ship one dylib per platform.
I didn't have a chance the test the MATLAB version. @amotta could you please help with that? Fixes #60

I also fixed a bug in the Morton-encoding and replaced the implementation with the one from the Scala code. I noticed the bug as I was trying to encode these two vectors `{ x: 29, y: 20, z: 3 }` and `{ x: 23, y: 20, z: 3 }` and the result was the same number `12333`. We haven't noticed this issue over the years, because Morton-encoding is actually not used in the rust implementation: When reading, the buckets in a cube are iterated and Morton-*de*coding is used to check whether they match the requested bbox. I also added 2 more test cases for this bug.

My IDE also formatted the code with the latest `rustfmt`.

### CODE REVIEW

File: rust/src/lz4_binding.rs [hunk 1]
```diff
@@ -0,0 +1,46 @@
+extern crate lz4;
```
Comment (amotta) [inline rust/src/lz4_binding.rs:1]: Personally, I am not a big fan of the `lz4_binding` name. We now have a stack of `lz4-sys`, `lz4` and `lz4_binding`.

If we could define a `wkwrap::lz4` submodule, I'd prefer that. But, obviously, that's not a deal-breaker.

File: rust/src/morton.rs [hunk 2]
```diff
@@ -4,45 +4,43 @@ use {Box3, Result, Vec3};
...
-            (shuffle(vec.x as u64))
-                | (shuffle(vec.y as u64) << 1)
-                | (shuffle(vec.z as u64) << 2),
-        )
+        let x = vec.x as u64;
+        let y = vec.y as u64;
+        let z = vec.z as u64;
+        let mut idx = 0u64;
+        let bit_length = 64 - (std::cmp::max(x, std::cmp::max(y, z)) + 1).leading_zeros();
+        for i in 0..bit_length {
```
Comment (amotta) [inline rust/src/morton.rs:14]: Hmm, not a big fan of this. The code use to be constant-time. Now it's linear in the number of significant _bits_.

Do we understand the problem with the previous implementation? I'd prefer to fix that.

**Review by amotta — COMMENTED** [review]
Hi Norman!

Thanks a lot! I really like how this simplifies building and using the library!

Earlier this year, I've started to hack on something similar. The goal was to address issue #60. However, I never got it to work across Windows, macOS and Linux. So, this fix is much appreciated!

Unfortunately, I don't have a lot of time right now and can't properly review this pull request.

I've successfully compiled and tested the MATLAB part on Linux. That seemed to work as intended. So, these are no blocking issues from my side. I've only left a few high-level comments for you to consider.

File: rust/src/morton.rs (hunk 2 above)
Comment (philippotto) [reply rust/src/morton.rs:14]: I also wondered about this and researched a bit. I found this blog post https://www.forceflow.be/2013/10/07/morton-encodingdecoding-through-bit-interleaving-implementations/ which compares several approaches for implementing the morton encoding/decoding. Maybe the implementations in this diff were even based on that post? Either way, the post includes 3 (in my opinion) interesting details:

- in addition to the for-loop and to the magic-bit approach, there is also a lookup-table based approach (might be the best of both worlds?)
- the post has the disclaimer "The code used in this post is outdated and might have bugs." (which could explain why the old implementation of this library is buggy)
- the post refers to the C++ based `libmorton` library which is recommended (as it contains further improvements and fixes).

So, maybe it would be for the best to make use of the library? That would reduce the complexity on the wkw side, as well. Alternatively, we could try to gain insights from their sourcecode (this [file](https://github.com/Forceflow/libmorton/blob/main/libmorton/morton3D.h) would be most interesting probably). The relevant code functions seem to be rather short.

As another high-level thought: it's not really clear whether this code path is a bottleneck, is it? maybe it doesn't matter in the end. Nevertheless, using a prebaked solution sounds good to me.

Comment (normanrz) [reply rust/src/morton.rs:14]: I think the perf-hit is negligible, since the Vec3 only has 32-bit components. That means the loop will be executed at max 32 times. In practice the loop will be called at max 5 times, bc the the bucket addresses within a file are at max 32. All operations in the loop are very cheap bit-operations on register values. The `leading_zeros` op is also a single CPU instruction.

> As another high-level thought: it's not really clear whether this code path is a bottleneck, is it?

My guess would be: absolutely not. Fetching a lookup table from uncached ram into register is probably slower than running this function.

I wouldn't want to pull in a lib (especially not a non-rust lib) for this due to the complexity at build time.

We could unroll the loop, but that would need to be dependent on `blocksPerFileDimLog2`.

File: rust/src/morton.rs [hunk 3]
```diff
@@ -4,45 +4,43 @@ use {Box3, Result, Vec3};
 #[derive(PartialEq, Debug)]
 pub struct Morton(u64);
 
-fn shuffle(v: u64) -> u64 {
-    // take first 21 bits
-    let mut z = v & 0x00000000001fffff;
-    z = (z | (z << 32)) & 0x001f00000000ffff;
-    z = (z | (z << 16)) & 0x001f0000ff0000ff;
-    z = (z | (z << 8)) & 0x100f00f00f00f00f;
-    z = (z | (z << 4)) & 0x100f00f00f00f00f;
```
Comment (amotta) [inline rust/src/morton.rs:13]: Here's the bug: The constant should be 0x10c30c30c30c30c3.
See https://github.com/Forceflow/libmorton/blob/24b63e34b1b3b5591fd10575c89ef1e5d1bb3e2a/libmorton/morton3D.h#L229

File: rust/README.md [hunk 4]
```diff
@@ -9,9 +9,7 @@ $ cargo build
 ```
 
 This requires the [Rust compiler and build tools](https://www.rust-lang.org/en-US/install.html)
```
[the remark this answers is not in the document]
Comment (normanrz) [reply rust/README.md:11]: That is an interesting question. `lz4` uses `lz4-sys` which uses `cc` for compilation of the c lib. Seems like `cc` requires an installed c compiler. We could list it in the readme, but chances are that users with a rust compiler will also have a cc installed.

File: rust/src/morton.rs (hunk 3 above)
Comment (philippotto) [reply rust/src/morton.rs:13]: :+1: 
This is the relevant issue https://github.com/Forceflow/libmorton/issues/25 and here's the relevant commit: https://github.com/Forceflow/libmorton/commit/d0d8c2c85dd16cec27a2703c8e89623c9a082503

File: rust/src/morton.rs (hunk 2 above)
Comment (normanrz) [reply rust/src/morton.rs:14]: I implemented @amotta's fix in https://github.com/scalableminds/webknossos-wrap/compare/lz4-crate...re-morton. Seems to work fine.

**Comment by normanrz** [comment]
@philippotto @valentin-pinkau ping for review

**Review by philippotto — APPROVED** [review]
Looks good to me :+1:
